# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
    - $HOME/.m2

language: java

jdk: openjdk11

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "Xg7ERaJ+8TFkg/lBG6KSKwpQ/Wmw8/TdvyHagphCpGtlp8uAM92igOvXAWvzgnnQxmcPh9Ks0Z5/dJuSVTtxydIqKkac3LXa4AucHe7sxJSHBwFSy0WuWN4Apuvp3uglantjwxc+OEKF9LYI5IgEWW3IS7UD7zvlXPuJ0AjdeP0="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "ipXMdXTjN7Ilg+bxjYFXixrBVT5dr/TFKIMH54vCuirrPXkvccCXaMCndk+eN+pprlgjcNBqtb0j/TGAfasdX0jSxOeyAUv5E0hxuXDURZ/OQUEpo7YMjLXrAT1/lg8f343TLJnjujeyuabvMdmFcY9o6HWc+MqB4ZGzNgYNiQo="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "PpQs4Eje8IYrCzLBWEv5nc2RL7XPubwhlFps4MO/LUvDg05cJpX4/rj5D0C99O9X9V9RnkDrvDkGxG02dwxZ6E1ciPheL7sGVDYlG75yDNipdSFGErNNH1W1wy4Q4PFbNg0i+vOB7MZas+MyGTZi7aZieX2f/ikVZvieCYoWwh8="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "Z6aQmONN3znLNtaMdt4ycoyHGdVqSC9W8N3FluZZFFYcoqhtR+p4RMWjpgloQHPZadLLuJIUijQgCYELCAFFkaIcanytIxWnVgK5/qpdfv7Vx52d5mwyCGq3jFtreVRNsd/4g6vkStr4nRf0+dZcDA4Y10CAlsZloF9ETPqQmco="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "GY48c/XSiQ87QC7HadzzdXKeymnLYdkwrWliaZzD2djSOv2pgmDMrW05jxIN+81B4w9CcM8R18KsUjpkATWKIctl/+/9sXMlQcvRMdM3EFA66RJA7tg4BjRjRwSv7YQ+935dbCHB/C8Zw05TkUQMpbqtGzjpckGIhNViyOJWYIU="
